name:       naruto-unison
version:    0.1.0.0
github:     "naruto-user/naruto-unison"
license:    BSD3
author:     "Naruto Unison"
maintainer: "joshua.n.booth@gmail.com"

dependencies:
- blaze-html
- blaze-markup
- cache
- clock
- mime-mail
- monad-loops
- mtl
- mwc-random
- transformers
- yesod-websockets

- elm-bridge
- foreign-store

- base
- yesod
- yesod-core
- yesod-auth
- yesod-static
- yesod-form
- classy-prelude
- bytestring
- text
- persistent
- persistent-postgresql
- persistent-template
- template-haskell
- shakespeare
- hjsmin
- wai-extra
- yaml
- http-client-tls
- http-conduit
- warp
- data-default
- aeson
- monad-logger
- fast-logger
- wai-logger
- file-embed
- unordered-containers
- containers
- vector
- time
- case-insensitive
- wai

library:
  source-dirs: src
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -Wincomplete-uni-patterns
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wredundant-constraints
      - -Wpartial-type-signatures
      - -fwarn-tabs
      - -fwarn-incomplete-patterns
      - -fwarn-incomplete-uni-patterns
      - -fno-warn-type-defaults
      - -funbox-small-strict-fields
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -Wincomplete-uni-patterns
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wredundant-constraints
      - -Wpartial-type-signatures
      - -fwarn-tabs
      - -fwarn-incomplete-patterns
      - -fwarn-incomplete-uni-patterns
      - -fno-warn-type-defaults
      - -funbox-small-strict-fields
      - -O2

# Runnable executable for our application
executables:
  naruto-unison:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - naruto-unison
    when:
    - condition: flag(library-only)
      buildable: false
  elm:
    main: elm.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - naruto-unison
    when:
    - condition: flag(library-only)
      buildable: false

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false

default-extensions:
# Package-specific
- NoImplicitPrelude
# Removing artificial limitations
- ConstraintKinds
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- InstanceSigs
- MultiParamTypeClasses
# Syntactic sugar
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- RecordWildCards
- ParallelListComp
- TupleSections
- UnicodeSyntax
- ViewPatterns
- MonadComprehensions
- BlockArguments
# More powerful types
- TypeFamilies
# More powerful deriving
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- GeneralizedNewtypeDeriving
- StandaloneDeriving
- ScopedTypeVariables
# Unlikely to be used, but no drawbacks
- BangPatterns
- DefaultSignatures
- KindSignatures
- PartialTypeSignatures
- PatternSynonyms
- RankNTypes
- TypeApplications
- TypeOperators
# Literals
- BinaryLiterals
- NegativeLiterals
- NumDecimals
# Unfortunate necessities
- OverloadedStrings
# Here Be Dragons
- StrictData
