name:       naruto-unison
version:    0.1.0.0
github:     "naruto-unison/naruto-unison"
license:    BSD3
author:     "Naruto Unison"
maintainer: "joshua.n.booth@gmail.com"

library:
  source-dirs: src
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -Wcompat
      - -Widentities
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wpartial-fields
      - -Wpartial-type-signatures
      - -Wredundant-constraints
      - -fwarn-tabs
      - -fwarn-incomplete-patterns
      - -fwarn-incomplete-uni-patterns
      - -funbox-small-strict-fields
      - -ferror-spans
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -Wincomplete-uni-patterns
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wredundant-constraints
      - -Wpartial-type-signatures
      - -fwarn-tabs
      - -fwarn-incomplete-patterns
      - -fwarn-incomplete-uni-patterns
      - -funbox-small-strict-fields
      - -ferror-spans
      - -O2
  dependencies:
  - aeson == 1.4.4.0
  - base == 4.12.0.0
  - blaze-html == 0.9.1.1
  - blaze-markup == 0.8.2.2
  - bounded-enum == 0.1.0.0
  - bytestring == 0.10.8.2
  - cache == 0.1.1.2
  - case-insensitive == 1.2.0.11
  - classy-prelude == 1.5.0
  - containers == 0.6.0.1
  - data-default == 0.7.1.1
  - esqueleto == 3.0.0
  - fast-logger == 2.4.17
  - file-embed == 0.0.11
  - hjsmin == 0.2.0.2
  - http-client-tls == 0.3.5.3
  - http-conduit == 2.3.7.1
  - http-types == 0.12.3
  - mime-mail == 0.5.0
  - monad-logger == 0.3.30
  - monad-loops == 0.4.3
  - mtl == 2.2.2
  - mwc-random == 0.14.0.0
  - persistent == 2.9.2
  - persistent-postgresql == 2.9.1
  - persistent-template == 2.6.0
  - shakespeare == 2.0.21
  - template-haskell == 2.14.0.0
  - text == 1.2.3.1
  - time == 1.8.0.2
  - transformers == 0.5.6.2
  - unliftio == 0.2.12
  - unordered-containers == 0.2.10.0
  - vector == 0.12.0.3
  - wai == 3.2.2.1
  - wai-extra == 3.0.28
  - wai-logger == 2.3.5
  - warp == 3.2.28
  - yaml == 0.11.1.2
  - yesod == 1.6.0
  - yesod-auth == 1.6.8
  - yesod-core == 1.6.16.1
  - yesod-form == 1.6.6
  - yesod-static == 1.6.0.1
  - yesod-websockets == 0.3.0.2

executables:
  naruto-unison:
    source-dirs: app/naruto-unison
    main: main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - naruto-unison
    - base
    when:
    - condition: flag(library-only)
      buildable: false
  elm-bridge:
    source-dirs: app/elm-bridge
    main: main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - naruto-unison
    - aeson
    - base
    - containers
    - elm-bridge == 0.5.2
    - template-haskell
    - text
    when:
    - condition: flag(library-only)
      buildable: false

tests:
  yesod-test:
    source-dirs: test
    main: Spec.hs
    dependencies:
    - naruto-unison
    - base
    - hspec == 2.7.1
    - transformers
    ghc-options:
      - -Wall
      - -Wincomplete-uni-patterns
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wredundant-constraints
      - -Wpartial-type-signatures
      - -fwarn-tabs
      - -fwarn-incomplete-patterns
      - -fwarn-incomplete-uni-patterns
      - -funbox-small-strict-fields

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false

default-extensions:
# Package-specific
- NoImplicitPrelude
# Removing artificial limitations
- ConstraintKinds
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- InstanceSigs
- MultiParamTypeClasses
# Syntactic sugar
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- RecordWildCards
- ParallelListComp
- TupleSections
- UnicodeSyntax
- ViewPatterns
- MonadComprehensions
- BlockArguments
- MagicHash
# More powerful types
- TypeFamilies
# More powerful deriving
- AutoDeriveTypeable
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- GeneralizedNewtypeDeriving
- StandaloneDeriving
- ScopedTypeVariables
# Unlikely to be used, but no drawbacks
- BangPatterns
- DefaultSignatures
- EmptyDataDecls
- KindSignatures
- PartialTypeSignatures
- PatternSynonyms
- RankNTypes
- TypeApplications
- TypeOperators
# Literals
- BinaryLiterals
- NegativeLiterals
- NumDecimals
# Unfortunate necessities
- OverloadedStrings
# Here Be Dragons
- ApplicativeDo
- StrictData
- UnboxedTuples
