name:       naruto-unison
version:    0.1.0.0
github:     "naruto-unison/naruto-unison"
license:    BSD3
author:     "Naruto Unison"
maintainer: "joshua.n.booth@gmail.com"

library:
  source-dirs: src
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -Wcompat
      - -Widentities
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wpartial-fields
      - -Wpartial-type-signatures
      - -Wredundant-constraints
      - -fwarn-tabs
      - -fwarn-incomplete-patterns
      - -fwarn-incomplete-uni-patterns
      - -funbox-small-strict-fields
      - -ferror-spans
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -Wincomplete-uni-patterns
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wredundant-constraints
      - -Wpartial-type-signatures
      - -fwarn-tabs
      - -fwarn-incomplete-patterns
      - -fwarn-incomplete-uni-patterns
      - -funbox-small-strict-fields
      - -ferror-spans
      - -O2
  dependencies:
  - aeson
  - attoparsec
  - base
  - bimap
  - blaze-html
  - blaze-markup
  - bounded-enum
  - bytestring
  - cache
  - case-insensitive
  - classy-prelude
  - containers
  - data-default
  - esqueleto
  - fast-logger
  - file-embed
  - hjsmin
  - http-client-tls
  - http-conduit
  - http-types
  - mime-mail
  - monad-logger
  - monad-loops
  - mtl
  - multimap
  - mwc-random
  - persistent
  - persistent-postgresql
  - persistent-template
  - shakespeare
  - template-haskell
  - text
  - time
  - transformers
  - unliftio
  - unordered-containers
  - vector
  - wai
  - wai-extra
  - wai-logger
  - warp
  - yaml
  - yesod
  - yesod-auth
  - yesod-core
  - yesod-form
  - yesod-static
  - yesod-websockets

executables:
  naruto-unison:
    source-dirs: app/naruto-unison
    main: main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - naruto-unison
    - base
    when:
    - condition: flag(library-only)
      buildable: false
  elm-bridge:
    source-dirs: app/elm-bridge
    main: main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wincomplete-uni-patterns
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wredundant-constraints
    - -Wpartial-type-signatures
    - -fwarn-tabs
    - -fwarn-incomplete-patterns
    - -fwarn-incomplete-uni-patterns
    - -funbox-small-strict-fields
    - -ferror-spans
    dependencies:
    - naruto-unison
    - aeson
    - base
    - containers
    - elm-bridge
    - template-haskell
    - text
    when:
    - condition: flag(library-only)
      buildable: false

tests:
  yesod-test:
    source-dirs: test
    main: Spec.hs
    dependencies:
    - naruto-unison
    - base
    - hspec
    - transformers
    ghc-options:
      - -Wall
      - -Wincomplete-uni-patterns
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wredundant-constraints
      - -Wpartial-type-signatures
      - -fwarn-tabs
      - -fwarn-incomplete-patterns
      - -fwarn-incomplete-uni-patterns
      - -funbox-small-strict-fields

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false

default-extensions:
# Package-specific
- NoImplicitPrelude
# Removing artificial limitations
- ConstraintKinds
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- InstanceSigs
- MultiParamTypeClasses
# Syntactic sugar
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- RecordWildCards
- ParallelListComp
- TupleSections
- UnicodeSyntax
- ViewPatterns
- MonadComprehensions
- BlockArguments
- MagicHash
# More powerful types
- TypeFamilies
# More powerful deriving
- AutoDeriveTypeable
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- GeneralizedNewtypeDeriving
- StandaloneDeriving
- ScopedTypeVariables
# Unlikely to be used, but no drawbacks
- BangPatterns
- DefaultSignatures
- EmptyDataDecls
- KindSignatures
- PartialTypeSignatures
- PatternSynonyms
- RankNTypes
- TypeApplications
- TypeOperators
# Literals
- BinaryLiterals
- NegativeLiterals
- NumDecimals
# Unfortunate necessities
- OverloadedStrings
# Here Be Dragons
- ApplicativeDo
- StrictData
- UnboxedTuples
